name: CI Static Frontend

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Log in to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Set lowercased repository owner
        run: echo "REPO_OWNER_LC=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV

      - name: Build and push Docker image
        run: |
          IMAGE=ghcr.io/${{ env.REPO_OWNER_LC}}/static-frontend
          docker build -t $IMAGE:sha-${{ github.sha }} .
          docker push $IMAGE:sha-${{ github.sha }}

#  update-infra:
#    runs-on: ubuntu-latest
#    needs: build-and-push
#    steps:
#      - name: Set lowercased repository owner
#        run: echo "REPO_OWNER_LC=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV
#
#      - name: Install yq
#        run: |
#          sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq
#          sudo chmod +x /usr/bin/yq

#      - name: Clone infra repo
#        run: |
#          git clone https://oauth2:${{ secrets.GITLAB_TOKEN }}@gitlab.com/dan6103605/infra.git
#          cd infra
#          git config user.email "ci@github"
#          git config user.name "GitHub Actions"
#
#          yq -i '.spec.template.spec.containers[0].image = "ghcr.io/${{ env.REPO_OWNER_LC}}/device-documentation:sha-${{ github.sha }}"' apps/frontend/static/deployment.yaml
#
#          git add apps/frontend/static/deployment.yaml
#          git commit -m "Update static-frontend image to sha-${{ github.sha }}"
#          git push origin main